### ISSUE TITLE
When recomender not activated, it's not obvious why

### ISSUE THREAD

**Issue by david-waterworth** [inception-project/inception-external-recommender#30]
My recommender suddenly stopped providing recommendations, retraining etc didn't help. I restarted the service and then noticed in the log:

> inception.jar[1647125]: 2021-07-15 13:09:52 INFO [admin] SelectionTask - [admin][[Custom Named Entity@value] Multi-Token Sequence Classifier (OpenNLP NER)]: Not activated (0.7135417217943837 < threshold 0.8999999761581421)

Followed by an exception - I'm not sure if they're related. In any case when the F1-score dropped below the threshold, the sidebar stopped providing any useful information. It would be helpful if I still had access to the confusion matrix, that way I'd know that the recommender accuracy was in fact below the threshold.

> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]: 2021-07-15 13:09:52 ERROR [admin] SelectionTask - [admin][[Custom Named Entity@value] Multi-Token Sequence Classifier (OpenNLP NER)]: Failed
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]: java.util.IllegalFormatConversionException: d != java.lang.Double
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4426) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2938) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter$FormatSpecifier.print(Formatter.java:2892) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter.format(Formatter.java:2673) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.Formatter.format(Formatter.java:2609) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.lang.String.format(String.java:2897) ~[?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.support.logging.LogMessage.<init>(LogMessage.java:49) ~[inception-support-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.support.logging.LogMessage.info(LogMessage.java:75) ~[inception-support-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.inception.recommendation.tasks.SelectionTask.execute(SelectionTask.java:230) [inception-recommendation-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.inception.scheduling.Task.run(Task.java:110) [inception-scheduling-0.20.0-rc-5.jar!/:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
> Jul 15 13:09:52 home-ubuntu-ml inception.jar[1647125]:         at java.lang.Thread.run(Thread.java:829) [?:?]
>

**Comment by david-waterworth** [comment]
Also this may be unrelated / a separate issue but once I lowered the threshold and tried to select the best recommendations the server log showed:

> inception.jar[1647125]: 2021-07-15 13:11:07 INFO [admin] SelectionTask - [admin][[BMS Named Entity@value] Multi-Token Sequence Classifier (OpenNLP NER)]: Activated (0.7135417217943837 >= threshold 0.6000000238418579)
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]: 2021-07-15 13:18:37 ERROR [admin] AnnotationPage - Error: null
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]: java.lang.NullPointerException: null
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.inception.recommendation.sidebar.RecommenderInfoPanel.actionAcceptBest(RecommenderInfoPanel.java:272) ~[inception-recommendation-0.20.0-rc-5.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.inception.recommendation.sidebar.RecommenderInfoPanel$1.lambda$populateItem$fa4ef610$1(RecommenderInfoPanel.java:171) ~[inception-recommendation-0.20.0-rc-5.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.support.lambda.LambdaAjaxLink.onClick(LambdaAjaxLink.java:67) [inception-support-0.20.0-rc-5.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.ajax.markup.html.AjaxLink$1.onEvent(AjaxLink.java:85) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:146) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:630) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.internalInvoke(ListenerRequestHandler.java:306) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.invoke(ListenerRequestHandler.java:280) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.invokeListener(ListenerRequestHandler.java:222) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.core.request.handler.ListenerRequestHandler.respond(ListenerRequestHandler.java:208) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:910) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.request.RequestHandlerExecutor.execute(RequestHandlerExecutor.java:63) [wicket-request-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:294) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:255) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:277) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.protocol.ws.AbstractUpgradeFilter.processRequestCycle(AbstractUpgradeFilter.java:67) [wicket-native-websocket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:208) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:307) [wicket-core-9.3.0.jar!/:9.3.0]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter.doFilterInternal(OpenEntityManagerInViewFilter.java:186) [spring-orm-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.support.logging.LoggingFilter.doFilter(LoggingFilter.java:58) [inception-support-0.20.0-rc-5.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at de.tudarmstadt.ukp.clarin.webanno.api.dao.casstorage.OpenCasStorageSessionForRequestFilter.doFilter(OpenCasStorageSessionForRequestFilter.java:50) [inception-api-dao-0.20.0-rc-5.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:327) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:105) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:101) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:92) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:147) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.session.ConcurrentSessionFilter.doFilter(ConcurrentSessionFilter.java:125) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183) [spring-security-web-5.4.7.jar!/:5.4.7]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.3.8.jar!/:5.3.8]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.45.jar!/:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]:         at java.lang.Thread.run(Thread.java:829) [?:?]
> Jul 15 13:18:37 home-ubuntu-ml inception.jar[1647125]: 2021-07-15 13:18:37 ERROR [admin] ApplicationPageBase - admin: Error: null
>
