### ISSUE TITLE
App Failed to load on command 

### ISSUE THREAD

**Issue by thak123** [inception-project/inception-external-recommender#6]
' gunicorn -w 4 -b 127.0.0.1:5000 wsgi:server._app
[2020-03-10 20:07:43 +0200] [27562] [INFO] Starting gunicorn 20.0.4
[2020-03-10 20:07:43 +0200] [27562] [INFO] Listening at: http://127.0.0.1:5000 (27562)
[2020-03-10 20:07:43 +0200] [27562] [INFO] Using worker: sync
[2020-03-10 20:07:43 +0200] [27565] [INFO] Booting worker with pid: 27565
[2020-03-10 20:07:43 +0200] [27566] [INFO] Booting worker with pid: 27566
[2020-03-10 20:07:43 +0200] [27567] [INFO] Booting worker with pid: 27567
[2020-03-10 20:07:43 +0200] [27568] [INFO] Booting worker with pid: 27568
Failed to parse 'server._app' as an attribute name or function call.
[2020-03-10 20:07:44 +0200] [27566] [INFO] Worker exiting (pid: 27566)
Failed to parse 'server._app' as an attribute name or function call.
[2020-03-10 20:07:44 +0200] [27565] [INFO] Worker exiting (pid: 27565)
Failed to parse 'server._app' as an attribute name or function call.
[2020-03-10 20:07:44 +0200] [27567] [INFO] Worker exiting (pid: 27567)
Failed to parse 'server._app' as an attribute name or function call.
[2020-03-10 20:07:44 +0200] [27568] [INFO] Worker exiting (pid: 27568)
Traceback (most recent call last):
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
    raise HaltServer(reason, self.APP_LOAD_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaurish/miniconda3/bin/gunicorn", line 11, in <module>
    load_entry_point('gunicorn==20.0.4', 'console_scripts', 'gunicorn')()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/gaurish/miniconda3/lib/python3.7/site-packages/gunicorn/arbiter.py", line 528, in reap_workers
    raise HaltServer(reason, self.APP_LOAD_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 
'

**Comment by jcklie** [comment]
Can you add the following line to the end of `wsgi.py` 

`app = server._app`

and try again 

`gunicorn -w 4 -b 127.0.0.1:5000 wsgi:app`

**Comment by jcklie** [comment]
For development, I recommend to directly run the recommender and not via gunicorn.

**Comment by thak123** [comment]
How do I run it in python ??? python wsgi.py??

**Comment by jcklie** [comment]
You copy the code from https://github.com/inception-project/inception-external-recommender#starting-a-simple-recommender into a script and call it.
